package main

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
)

// GenIdentity is the generated identity of one parser.
type GenIdentity struct{ Package, Hash string }

// GenerateIdentity returns the bytes of internal/parsers/identity_gen.go for
// ids (key "name@version"), keys sorted. The text is already in gofumpt form.
func GenerateIdentity(ids map[string]GenIdentity) []byte {
	var b bytes.Buffer
	b.WriteString(`// Code generated by the parser hash generator; DO NOT EDIT.

package parsers

// identity is the generated identity of one parser: the package that defines it
// and the hash of its source.
type identity struct{ Package, Hash string }

// generated maps "name@version" to the identity of the parser.
`)
	if len(ids) == 0 {
		b.WriteString("var generated = map[string]identity{}\n")
	} else {
		keys := make([]string, 0, len(ids))
		for k := range ids {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		b.WriteString("var generated = map[string]identity{\n")
		for _, k := range keys {
			id := ids[k]
			fmt.Fprintf(&b, "\t%s: {Package: %s, Hash: %s},\n", strconv.Quote(k), strconv.Quote(id.Package), strconv.Quote(id.Hash))
		}
		b.WriteString("}\n")
	}
	out, err := format.Source(b.Bytes())
	if err != nil {
		panic("parserhash: generated source does not parse: " + err.Error())
	}
	return out
}
