package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const genHeader = `// Code generated by the parser hash generator; DO NOT EDIT.

package parsers

// identity is the generated identity of one parser: the package that defines it
// and the hash of its source.
type identity struct{ Package, Hash string }

// generated maps "name@version" to the identity of the parser.
`

const (
	hA = "src1:sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
	hB = "src1:sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
)

// The expected text is written out by hand, not produced by the generator.
func TestGenerateIdentityGolden(t *testing.T) {
	want := genHeader + "var generated = map[string]identity{\n" +
		"\t\"alpha@1.2.3\": {Package: \"example.test/m/internal/parsers/x\", Hash: \"" + hA + "\"},\n" +
		"\t\"beta@1.0.0\":  {Package: \"example.test/m/internal/parsers/y\", Hash: \"" + hB + "\"},\n" +
		"}\n"
	got := string(GenerateIdentity(map[string]GenIdentity{
		"beta@1.0.0":  {Package: "example.test/m/internal/parsers/y", Hash: hB},
		"alpha@1.2.3": {Package: "example.test/m/internal/parsers/x", Hash: hA},
	}))
	if got != want {
		t.Errorf("generated text differs:\n got: %q\nwant: %q", got, want)
	}
	if empty := string(GenerateIdentity(nil)); empty != genHeader+"var generated = map[string]identity{}\n" {
		t.Errorf("empty registry text: %q", empty)
	}
}

// Name and package directory differ, so keying by Name, or swapping Package
// and Hash, produces different text.
func TestWriteGoldenForNonEmptyRegistry(t *testing.T) {
	root := writeTree(t, map[string]string{
		"internal/parsers/x/x.go": "package x\n\nconst V = 1\n",
		"internal/parsers/y/y.go": "package y\n\nconst V = 2\n",
		lockRel:                   "",
		genRel:                    "",
	})
	entries := []Entry{
		{Name: "beta", Version: "1.0.0", Package: testModule + "/internal/parsers/y"},
		{Name: "alpha", Version: "1.2.3", Package: testModule + "/internal/parsers/x"},
	}
	hx, hy := hashTree(t, root, "internal/parsers/x"), hashTree(t, root, "internal/parsers/y")
	if code, _, e := runCmd(t, root, entries, "-write"); code != 0 {
		t.Fatalf("write: %d %q", code, e)
	}
	gotGen, _ := os.ReadFile(filepath.Join(root, filepath.FromSlash(genRel)))
	wantGen := genHeader + "var generated = map[string]identity{\n" +
		"\t\"alpha@1.2.3\": {Package: \"" + testModule + "/internal/parsers/x\", Hash: \"" + hx + "\"},\n" +
		"\t\"beta@1.0.0\":  {Package: \"" + testModule + "/internal/parsers/y\", Hash: \"" + hy + "\"},\n" +
		"}\n"
	if string(gotGen) != wantGen {
		t.Errorf("identity_gen.go:\n got: %q\nwant: %q", gotGen, wantGen)
	}
	gotLock, _ := os.ReadFile(filepath.Join(root, filepath.FromSlash(lockRel)))
	wantLock := "# parsers.lock: the generated source hash of every compiled-in parser, locked by version.\n" +
		"alpha 1.2.3 " + hx + "\n" +
		"beta 1.0.0 " + hy + "\n"
	if string(gotLock) != wantLock {
		t.Errorf("parsers.lock:\n got: %q\nwant: %q", gotLock, wantLock)
	}
	if code, _, e := runCmd(t, root, entries, "-check"); code != 0 {
		t.Errorf("check after write: %d %q", code, e)
	}
}

func TestLockRefusesTrailingFieldAndCRInComment(t *testing.T) {
	for name, in := range map[string]string{
		"trailing field":  "a 1.0.0 " + h64 + " extra\n",
		"CR in a comment": "# c\r\na 1.0.0 " + h64 + "\n",
	} {
		if _, err := ParseLock([]byte(in)); err == nil {
			t.Errorf("%s: accepted", name)
		}
	}
}

func TestLockHighestIsTheNumericallyHighestVersion(t *testing.T) {
	l, err := ParseLock([]byte("a 1.0.9 " + h64 + "\na 1.0.10 " + h64 + "\nb 2.0.0 " + h64 + "\n"))
	if err != nil {
		t.Fatal(err)
	}
	for name, want := range map[string]string{"a": "1.0.10", "b": "2.0.0"} {
		if got, ok := l.highest(name); !ok || got != want {
			t.Errorf("highest(%s) = %q %v, want %q", name, got, ok, want)
		}
	}
	if _, ok := l.highest("c"); ok {
		t.Error("highest of an unlocked name")
	}
}

func TestWriteSortsTheLockByNameThenNumericVersion(t *testing.T) {
	root := writeTree(t, map[string]string{
		"internal/parsers/a/a.go": "package a\n",
		"internal/parsers/b/b.go": "package b\n",
		lockRel:                   "# h\n",
		genRel:                    "",
	})
	pkg := func(n string) string { return testModule + "/internal/parsers/" + n }
	entries := []Entry{
		{Name: "b", Version: "1.0.0", Package: pkg("b")},
		{Name: "a", Version: "1.0.10", Package: pkg("a")},
		{Name: "a", Version: "1.0.9", Package: pkg("a")},
	}
	next, _, added, err := Write(testConfig(root), entries, Lock{Header: []string{"# h"}})
	if err != nil {
		t.Fatal(err)
	}
	var order []string
	for _, ln := range next.Lines {
		order = append(order, ln.Name+" "+ln.Version)
	}
	if got := strings.Join(order, ","); got != "a 1.0.9,a 1.0.10,b 1.0.0" {
		t.Errorf("lock order = %s", got)
	}
	if len(added) != 3 {
		t.Errorf("added %d lines, want 3", len(added))
	}
	if _, err := ParseLock(next.Format()); err != nil {
		t.Errorf("written lock does not parse: %v", err)
	}
}

func TestWriteRefusesPackageOutsideParsers(t *testing.T) {
	root := parserTree(t, pSrc)
	before, _ := os.ReadFile(filepath.Join(root, filepath.FromSlash(lockRel)))
	e := []Entry{{Name: "p", Version: "1.0.0", Package: testModule + "/internal/other/p"}}
	if _, _, _, err := Write(testConfig(root), e, Lock{}); err == nil || !strings.Contains(err.Error(), "outside") {
		t.Errorf("Write: %v", err)
	}
	if code, _, msg := runCmd(t, root, e, "-write"); code != 1 || !strings.Contains(msg, "outside") {
		t.Errorf("-write: %d %q", code, msg)
	}
	if after, _ := os.ReadFile(filepath.Join(root, filepath.FromSlash(lockRel))); string(after) != string(before) {
		t.Error("the lock changed")
	}
}

func TestResolveErrorsPropagate(t *testing.T) {
	root := parserTree(t, "package p\nfunc (")
	if _, err := Check(testConfig(root), pEntry("1.0.0"), Lock{}, nil); err == nil {
		t.Error("Check swallowed a hashing error")
	}
	if _, _, _, err := Write(testConfig(root), pEntry("1.0.0"), Lock{}); err == nil {
		t.Error("Write swallowed a hashing error")
	}
	for _, flag := range []string{"-check", "-write"} {
		if code, _, e := runCmd(t, root, pEntry("1.0.0"), flag); code != 1 || e == "" {
			t.Errorf("%s: %d %q", flag, code, e)
		}
	}
}

func TestWriteGivesAnEmptyLockItsDefaultHeader(t *testing.T) {
	root := writeTree(t, map[string]string{lockRel: "", genRel: ""})
	if code, _, e := runCmd(t, root, nil, "-write"); code != 0 {
		t.Fatalf("write: %d %q", code, e)
	}
	got, _ := os.ReadFile(filepath.Join(root, filepath.FromSlash(lockRel)))
	if want := "# parsers.lock: the generated source hash of every compiled-in parser, locked by version.\n"; string(got) != want {
		t.Errorf("default header: %q", got)
	}
}

// A read failure while hashing (after the scope resolved) must end the command.
func TestHashingReadFailurePropagates(t *testing.T) {
	root := parserTree(t, pSrc)
	old := readFile
	readFile = func(string) ([]byte, error) { return nil, os.ErrPermission }
	defer func() { readFile = old }()
	if _, err := Check(testConfig(root), pEntry("1.0.0"), Lock{}, nil); err == nil {
		t.Error("Check swallowed a hashing error")
	}
	if _, _, _, err := Write(testConfig(root), pEntry("1.0.0"), Lock{}); err == nil {
		t.Error("Write swallowed a hashing error")
	}
}
