// Code generated by the parser hash generator; DO NOT EDIT.

package parsers

// identity is the generated identity of one parser: the package that defines it
// and the hash of its source.
type identity struct{ Package, Hash string }

// generated maps "name@version" to the identity of the parser. It is empty in 4A.
var generated = map[string]identity{}
